export const AllStates = [
  {
    id: 2,
    code: "IND035",
    name: "ANDAMAN AND NICOBAR ISLANDS",
    codeMap: "IN-AN",
    mapName: "Andaman & Nicobar Island",
  },
  {
    id: 3,
    code: "IND028",
    name: "ANDHRA PRADESH",
    codeMap: "IN-AP",
    mapName: "Andhra Pradesh",
  },
  {
    id: 4,
    code: "IND012",
    name: "ARUNACHAL PRADESH",
    codeMap: "IN-AR",
    mapName: "Arunachal Pradesh",
  },
  {
    id: 5,
    code: "IND018",
    name: "ASSAM",
    codeMap: "IN-AS",
    mapName: "Assam",
  },
  {
    id: 6,
    code: "IND010",
    name: "BIHAR",
    codeMap: "IN-BR",
    mapName: "Bihar",
  },
  {
    id: 7,
    code: "IND004",
    name: "CHANDIGARH",
    codeMap: "IN-CH",
    mapName: "Chandigarh",
  },
  {
    id: 8,
    code: "IND022",
    name: "CHHATTISGARH",
    codeMap: "IN-CT",
    mapName: "Chhattisgarh",
  },
  {
    id: 9,
    code: "IND038",
    name: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    codeMap: "IN-DN",
    mapName: "Dadara & Nagar Haveli",
  },
  {
    id: 10,
    code: "IND007",
    name: "DELHI",
    codeMap: "IN-DL",
    mapName: "Delhi",
  },
  {
    id: 11,
    code: "IND030",
    name: "GOA",
    codeMap: "IN-GA",
    mapName: "Goa",
  },
  {
    id: 12,
    code: "IND024",
    name: "GUJARAT",
    codeMap: "IN-GJ",
    mapName: "Gujarat",
  },
  {
    id: 13,
    code: "IND006",
    name: "HARYANA",
    codeMap: "IN-HR",
    mapName: "Haryana",
  },
  {
    id: 14,
    code: "IND002",
    name: "HIMACHAL PRADESH",
    codeMap: "IN-HP",
    mapName: "Himachal Pradesh",
  },
  {
    id: 15,
    code: "IND001",
    name: "JAMMU AND KASHMIR",
    codeMap: "IN-JK",
    mapName: "Jammu & Kashmir",
  },
  {
    id: 16,
    code: "IND020",
    name: "JHARKHAND",
    codeMap: "IN-JH",
    mapName: "Jharkhand",
  },
  {
    id: 17,
    code: "IND029",
    name: "KARNATAKA",
    codeMap: "IN-KA",
    mapName: "Karnataka",
  },
  {
    id: 18,
    code: "IND032",
    name: "KERALA",
    codeMap: "IN-KL",
    mapName: "Kerala",
  },
  {
    id: 19,
    code: "IND037",
    name: "LADAKH",
    codeMap: "IN-LA",
    mapName: "Ladakh",
  },
  {
    id: 20,
    code: "IND031",
    name: "LAKSHADWEEP",
    codeMap: "IN-LD",
    mapName: "Lakshadweep",
  },
  {
    id: 21,
    code: "IND023",
    name: "MADHYA PRADESH",
    codeMap: "IN-MP",
    mapName: "Madhya Pradesh",
  },
  {
    id: 22,
    code: "IND027",
    name: "MAHARASHTRA",
    codeMap: "IN-MH",
    mapName: "Maharashtra",
  },
  {
    id: 23,
    code: "IND014",
    name: "MANIPUR",
    codeMap: "IN-MN",
    mapName: "Manipur",
  },
  {
    id: 24,
    code: "IND017",
    name: "MEGHALAYA",
    codeMap: "IN-ML",
    mapName: "Meghalaya",
  },
  {
    id: 25,
    code: "IND015",
    name: "MIZORAM",
    codeMap: "IN-MZ",
    mapName: "Mizoram",
  },
  {
    id: 26,
    code: "IND013",
    name: "NAGALAND",
    codeMap: "IN-NL",
    mapName: "Nagaland",
  },
  {
    id: 27,
    code: "IND021",
    name: "ODISHA",
    codeMap: "IN-OR",
    mapName: "Odisha",
  },
  {
    id: 28,
    code: "IND034",
    name: "PUDUCHERRY",
    codeMap: "IN-PY",
    mapName: "Puducherry",
  },
  {
    id: 29,
    code: "IND003",
    name: "PUNJAB",
    codeMap: "IN-PB",
    mapName: "Punjab",
  },
  {
    id: 30,
    code: "IND008",
    name: "RAJASTHAN",
    codeMap: "IN-RJ",
    mapName: "Rajasthan",
  },
  {
    id: 31,
    code: "IND011",
    name: "SIKKIM",
    codeMap: "IN-SK",
    mapName: "Sikkim",
  },
  {
    id: 32,
    code: "IND033",
    name: "TAMIL NADU",
    codeMap: "IN-TN",
    mapName: "Tamil Nadu",
  },
  {
    id: 33,
    code: "IND036",
    name: "TELANGANA",
    mapName: "Telangana",
  },
  {
    id: 34,
    code: "IND016",
    name: "TRIPURA",
    codeMap: "IN-TR",
    mapName: "Tripura",
  },
  {
    id: 35,
    code: "IND009",
    name: "UTTAR PRADESH",
    codeMap: "IN-UP",
    mapName: "Uttar Pradesh",
  },
  {
    id: 36,
    code: "IND005",
    name: "UTTARAKHAND",
    codeMap: "IN-UT",
    mapName: "Uttarakhand",
  },
  {
    id: 37,
    code: "IND019",
    name: "WEST BENGAL",
    codeMap: "IN-WB",
    mapName: "West Bengal",
  },
];
