export const ODFStatus = [
  {
    State: "Andaman & Nicobar Islands",
    ODF: 0,
    ODFPlus: 0,
    ODFPlusPlus: 1,
    WaterPlus: 0,
    Total: 1,
  },
  {
    State: "Andhra Pradesh",
    ODF: 13,
    ODFPlus: 18,
    ODFPlusPlus: 6,
    WaterPlus: 3,
    Total: 40,
  },
  {
    State: "Arunachal Pradesh",
    ODF: 1,
    ODFPlus: 0,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 1,
  },
  {
    State: "Assam",
    ODF: 2,
    ODFPlus: 13,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 15,
  },
  {
    State: "Bihar",
    ODF: 7,
    ODFPlus: 15,
    ODFPlusPlus: 1,
    WaterPlus: 0,
    Total: 23,
  },
  {
    State: "Chandigarh",
    ODF: 0,
    ODFPlus: 0,
    ODFPlusPlus: 0,
    WaterPlus: 1,
    Total: 1,
  },
  {
    State: "Chhattisgarh",
    ODF: 0,
    ODFPlus: 3,
    ODFPlusPlus: 160,
    WaterPlus: 0,
    Total: 163,
  },
  {
    State: "Daman Diu And Dadra Nagar Haveli",
    ODF: 0,
    ODFPlus: 3,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 3,
  },
  {
    State: "Delhi",
    ODF: 1,
    ODFPlus: 0,
    ODFPlusPlus: 1,
    WaterPlus: 1,
    Total: 3,
  },
  {
    State: "Goa",
    ODF: 0,
    ODFPlus: 3,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 3,
  },
  {
    State: "Gujarat",
    ODF: 8,
    ODFPlus: 13,
    ODFPlusPlus: 85,
    WaterPlus: 1,
    Total: 107,
  },
  {
    State: "Haryana",
    ODF: 2,
    ODFPlus: 38,
    ODFPlusPlus: 11,
    WaterPlus: 0,
    Total: 51,
  },
  {
    State: "Himachal Pradesh",
    ODF: 2,
    ODFPlus: 6,
    ODFPlusPlus: 2,
    WaterPlus: 0,
    Total: 10,
  },
  {
    State: "Jammu & Kashmir",
    ODF: 0,
    ODFPlus: 10,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 10,
  },
  {
    State: "Jharkhand",
    ODF: 8,
    ODFPlus: 23,
    ODFPlusPlus: 3,
    WaterPlus: 0,
    Total: 34,
  },
  {
    State: "Karnataka",
    ODF: 6,
    ODFPlus: 68,
    ODFPlusPlus: 6,
    WaterPlus: 1,
    Total: 81,
  },
  {
    State: "Kerala",
    ODF: 4,
    ODFPlus: 44,
    ODFPlusPlus: 1,
    WaterPlus: 0,
    Total: 49,
  },
  {
    State: "Madhya Pradesh",
    ODF: 30,
    ODFPlus: 10,
    ODFPlusPlus: 325,
    WaterPlus: 2,
    Total: 367,
  },
  {
    State: "Maharashtra",
    ODF: 10,
    ODFPlus: 89,
    ODFPlusPlus: 191,
    WaterPlus: 4,
    Total: 294,
  },
  {
    State: "Manipur",
    ODF: 0,
    ODFPlus: 9,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 9,
  },
  {
    State: "Meghalaya",
    ODF: 0,
    ODFPlus: 1,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 1,
  },
  {
    State: "Mizoram",
    ODF: 8,
    ODFPlus: 1,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 9,
  },
  {
    State: "Nagaland",
    ODF: 0,
    ODFPlus: 2,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 2,
  },
  {
    State: "Odisha",
    ODF: 0,
    ODFPlus: 53,
    ODFPlusPlus: 21,
    WaterPlus: 0,
    Total: 74,
  },
  {
    State: "Puducherry",
    ODF: 1,
    ODFPlus: 0,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 1,
  },
  {
    State: "Punjab",
    ODF: 4,
    ODFPlus: 59,
    ODFPlusPlus: 53,
    WaterPlus: 0,
    Total: 116,
  },
  {
    State: "Rajasthan",
    ODF: 8,
    ODFPlus: 61,
    ODFPlusPlus: 12,
    WaterPlus: 0,
    Total: 81,
  },
  {
    State: "Sikkim",
    ODF: 0,
    ODFPlus: 3,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 3,
  },
  {
    State: "Tamil Nadu",
    ODF: 6,
    ODFPlus: 245,
    ODFPlusPlus: 1,
    WaterPlus: 0,
    Total: 252,
  },
  {
    State: "Telangana",
    ODF: 4,
    ODFPlus: 67,
    ODFPlusPlus: 42,
    WaterPlus: 1,
    Total: 114,
  },
  {
    State: "Tripura",
    ODF: 0,
    ODFPlus: 5,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 5,
  },
  {
    State: "Uttar Pradesh",
    ODF: 64,
    ODFPlus: 455,
    ODFPlusPlus: 43,
    WaterPlus: 0,
    Total: 562,
  },
  {
    State: "Uttarakhand",
    ODF: 1,
    ODFPlus: 37,
    ODFPlusPlus: 3,
    WaterPlus: 0,
    Total: 41,
  },
  {
    State: "West Bengal",
    ODF: 68,
    ODFPlus: 7,
    ODFPlusPlus: 0,
    WaterPlus: 0,
    Total: 75,
  },
];
